# -*- coding: utf-8 -*-
"""Artificial Intelligence Tools Exercise 3 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wTo3TZU22WIdYh8wi6pLUxE-87s2cD97

# 0. The instructor draws an object for each student

Prowadzący losuje obiekt dla każdego studenta

# 1. Installing the Ultralytics library
Instalowanie biblioteki Ultralytics
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics

"""# 2. Importing the library and YOLO model into the program
Importowanie biblioteki i modelu YOLO do programu
"""

import ultralytics
ultralytics.checks()
from ultralytics import YOLO

"""# 3. Inference (image detection) on the image which is not in COCO dataset

Inferencja modelu na obrazie, który nie zawiera się w datasecie COCO

https://cocodataset.org/#explore
"""

!yolo classify predict model=yolov8n-cls.pt source='https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/French-power-socket.jpg/1200px-French-power-socket.jpg'

"""# 4. Roboflow library installing
Instalowanie biblioteki Roboflow


"""

!pip install roboflow --quiet

"""# 5. Finding the right dataset and importing it into the project
Znalezienie odpowiedniego datasetu i zaimportowanie go do projektu

You need to find a ready-made dataset with your object on the website: https://universe.roboflow.com/
"""

from roboflow import Roboflow
rf = Roboflow(api_key="u8msuu6wZaW4g1hTpIr6")
project = rf.workspace("yolov5-power-socket-detection").project("power-socket-detection-jbgd5")
version = project.version(1)
dataset = version.download("yolov8")

"""# 6. YOLOv8 network training
Trening sieci YOLOv8

"""

!yolo train model=yolov8n.pt data='/content/Power-Socket-Detection-1/data.yaml' epochs=3 imgsz=640 device=0

"""# 7. Re-inferencing the sample image
Ponowna inferencja z wykorzysaniem nowo-wytrenowanej sieci
"""

!yolo predict model=/content/runs/detect/train/weights/best.pt source='https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/French-power-socket.jpg/1200px-French-power-socket.jpg'

"""# 8. Validate the model and list some metrics that you think are important, e.g. 3

Przeprowadzić walidację modelu i wypisz kilka twoim zdaniem istotnych metryk, np. 3
"""

!yolo val model=/content/runs/detect/train/weights/best.pt data='/content/Power-Socket-Detection-1/data.yaml'

"""# 9. After finishing the work, please export the notebook to a .pdf file and send it as a response to the task on the elerning platform. Additionally, attach the final .jpg file with the detected object.

Po zakończeniu pracy eksportujemy notatnik do pliku .pdf i wysyłamy go jako odpowiedź do zadania na platformie elerningowej. Dodatkowo załączamy także ostateczny plik .jpg z wykrytem obiektem.


"""