# -*- coding: utf-8 -*-
"""Kopia notatnika Artificial Intelligence Tools - Exercise 3 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157iWDzJ5mt2FVy71hq9m9whuaXDYjMqR

# 0. The instructor draws an object for each student

Prowadzący losuje obiekt dla każdego studenta

# 1. Installing the Ultralytics library
Instalowanie biblioteki Ultralytics
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics==8.0.196

"""# 2. Importing the library and YOLO model into the program
Importowanie biblioteki i modelu YOLO do programu
"""

import ultralytics
ultralytics.checks()
from ultralytics import YOLO

"""# 3. Inference (image detection) on the image which is not in COCO dataset

Inferencja modelu na obrazie, który nie zawiera się w datasecie COCO

https://cocodataset.org/#explore
"""

!yolo classify predict model=yolov8n-cls.pt source='/01_200.png'

"""# 4. Roboflow library installing
Instalowanie biblioteki Roboflow


"""

!pip install roboflow --quiet

"""# 5. Finding the right dataset and importing it into the project
Znalezienie odpowiedniego datasetu i zaimportowanie go do projektu

You need to find a ready-made dataset with your object on the website: https://universe.roboflow.com/
"""

from roboflow import Roboflow
rf = Roboflow(api_key="u8msuu6wZaW4g1hTpIr6")
project = rf.workspace("fatecharacter").project("fate-m89rb")
version = project.version(2)
dataset = version.download("yolov8")

"""# 6. YOLOv8 network training
Trening sieci YOLOv8

"""

!yolo train model=yolov8n.pt data='/content/Fate-2/data.yaml' epochs=80  device=0

"""# 7. Re-inferencing the sample image
Ponowna inferencja z wykorzysaniem nowo-wytrenowanej sieci
"""

!yolo predict model=/content/runs/detect/train/weights/best.pt source='/01_200.png'

"""# 8. Validate the model and list some metrics that you think are important, e.g. 3

Przeprowadzić walidację modelu i wypisz kilka twoim zdaniem istotnych metryk, np. 3
"""

!yolo val model=/content/runs/detect/train/weights/best.pt data='/content/Fate-2/data.yaml'

"""# 9. After finishing the work, please export the notebook to a .pdf file and send it as a response to the task on the elerning platform. Additionally, attach the final .jpg file with the detected object.

Po zakończeniu pracy eksportujemy notatnik do pliku .pdf i wysyłamy go jako odpowiedź do zadania na platformie elerningowej. Dodatkowo załączamy także ostateczny plik .jpg z wykrytem obiektem.


"""

!yolo classify predict model=yolov8m-cls.pt source='/01_200.png'

!yolo train model=yolov8m.pt data='/content/Fate-2/data.yaml' epochs=80  device=0

!yolo predict model=/content/runs/detect/train2/weights/best.pt source='/01_200.png'

!yolo val model=/content/runs/detect/train2/weights/best.pt data='/content/Fate-2/data.yaml'